mp.messaging.connector.smallrye-kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=${KAFKA_TOPIC_MESSAGES:jbossqueues.messages}
mp.messaging.outgoing.messages-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-out.acks=all
mp.messaging.outgoing.messages-out.retries=3
mp.messaging.outgoing.messages-out.retry.backoff.ms=${QUEUE_RETRY_BACKOFF_MILLIS:500}

mp.messaging.incoming.messages-in.connector=smallrye-kafka
mp.messaging.incoming.messages-in.topic=${KAFKA_TOPIC_MESSAGES:jbossqueues.messages}
mp.messaging.incoming.messages-in.group.id=${KAFKA_CONSUMER_GROUP:jbossqueues-demo}
mp.messaging.incoming.messages-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.auto.offset.reset=earliest
mp.messaging.incoming.messages-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.messages-in.dead-letter-queue.topic=${KAFKA_TOPIC_MESSAGES_DLQ:jbossqueues.messages.dlq}
